# Generated by Django 5.0.1 on 2024-03-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_head', models.TextField()),
                ('job_location', models.TextField()),
                ('job_qual1', models.TextField()),
                ('job_qual2', models.TextField()),
                ('job_qual3', models.TextField()),
            ],
        ),
    ]
