# Generated by Django 5.0.1 on 2024-03-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='age',
            new_name='areain',
        ),
    ]
