# Generated by Django 5.0.1 on 2024-03-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_age_details_areain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='father_name',
        ),
    ]
